#!/bin/sh

set -x
orgsize=65535    # orignal 63M size of Pi4 partition

#get size of the /mnt partition
mntsize=`df  | grep /mnt | sed  's|\s\+|,|g' | cut -d ',' -f 2`

cd /mnt

if [ -f recovery.rfs ]; then
	cp recovery.cmdline     /tmp/cmdline.txt
else
	cp cmdline.txt		/tmp/cmdline.txt
fi
cp config.txt		/tmp/config.bak

#REMOVE ALL BOOT FILES!
rm -rf *

#Restore saved settings
cp /tmp/cmdline.txt /mnt
cp /tmp/cmdline.txt /mnt/cmdline.bak
cp /tmp/config.bak /mnt

#if partition is still 63M, use the new wallpaper to save space
if [ $mntsize -lt $orgsize ]; then
	unzip /tmp/pinn-lite.zip wallpaper2.jpg
	mv wallpaper2.jpg wallpaper.jpg
	echo "wallpaper.jpg" >>/tmp/exclude.txt
	echo "cmdline.txt" >>/tmp/exclude.txt
	sync
fi

#Use new configuration
unzip -o /tmp/pinn-lite.zip config.txt

#Update the cmdline with saved info
#Just change the ramdisk_size
sed -i -e 's|runinstaller||' cmdline.txt
sed -i -e "s|ramdisk_size=32768|ramdisk_size=65536|" cmdline.txt

#Find out how much space we need for unzip
cd /tmp
exclude=
while read a; do
	if [ ${#a} -gt 0 ]; then
		exclude="${exclude} -x $a "
	fi
done < /tmp/exclude.txt
pi5minsize=$(expr 1520 + $(unzip -l /tmp/pinn-lite.zip $exclude |tail -n1 | sed 's|\s\+| |g'| sed 's|^ ||' | cut -d ' ' -f 1) / 1024)

freesize=`df  | grep /mnt | sed  's|\s\+|,|g' | cut -d ',' -f 4`


sync

if [ $freesize -lt $pi5minsize ]; then
        echo "Partition size Too small"
        exit 1
fi

exit 0
