#!/bin/sh

set -x
error=$1

if [ "x$error" == "x" ]; then
        error=0
fi

output="/tmp/mnt"

if [ ! $error -eq 0 ]; then
	#preupdate failed, so restore saved files.
	cp -a $output/* /mnt
	exit 1
fi

