#!/bin/bash

cp *.c ../buildroot/output/build/linux-12d78096b1669a08d440f7ebaddf5d925e52fe79/drivers/input/touchscreen/
cp *-overlay.dts ../buildroot/output/build/linux-12d78096b1669a08d440f7ebaddf5d925e52fe79/arch/arm/boot/dts/overlays/

